### ISSUE TITLE
Hangs at starting download

### ISSUE THREAD

**Issue by timf1256** [MinoMino/mindl#1]
Here is the console error:

```
(19:31 INFO) URL is being handled by plugin: eBookJapan v0.1
(19:31 INFO) Starting download...
(19:33:45 CRITICAL) [eBookJapan] Failed to find the controller. If it's a reader
 link, make sure it hasn't expired.
(19:33 CRITICAL) An uncaught exception was raised while downloading.
viewLayer qualitylayer None
Traceback (most recent call last):
  File "C:\Python\Python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python\Python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python35-32\lib\site-packages\mindl\__main__.py", line 117, in
 <module>
    main(parser.parse_args())
  File "C:\Python\Python35-32\lib\site-packages\mindl\__main__.py", line 106, in
 main
    dm.start_download()
  File "C:\Python\Python35-32\lib\site-packages\mindl\download_manager.py", line
 74, in start_download
    raise e
  File "C:\Python\Python35-32\lib\site-packages\mindl\download_manager.py", line
 40, in start_download
    for dl in self._plugin.downloader():
  File "C:\Python\Python35-32\lib\site-packages\mindl\plugins\ebookjapan.py", li
ne 119, in downloader
    raise e
  File "C:\Python\Python35-32\lib\site-packages\mindl\plugins\ebookjapan.py", li
ne 116, in downloader
    self.wait.until(EC.visibility_of_element_located((By.XPATH, "//div[@id='cont
roller']")))
  File "C:\Python\Python35-32\lib\site-packages\selenium\webdriver\support\wait.
py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

And here is the ghostdriver.log:

```
[INFO  - 2016-09-03T23:31:36.089Z] GhostDriver - Main - running on port 49860
[INFO  - 2016-09-03T23:31:37.337Z] Session [8eecbb40-722e-11e6-9041-c7422ee2d8e1] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0","webSecurityEnabled":false}
[INFO  - 2016-09-03T23:31:37.337Z] Session [8eecbb40-722e-11e6-9041-c7422ee2d8e1] - page.customHeaders:  - {}
[INFO  - 2016-09-03T23:31:37.337Z] Session [8eecbb40-722e-11e6-9041-c7422ee2d8e1] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"windows-7-32bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"},"phantomjs.page.settings.userAgent":"Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0"}
[INFO  - 2016-09-03T23:31:37.337Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 8eecbb40-722e-11e6-9041-c7422ee2d8e1
[ERROR - 2016-09-03T23:31:51.671Z] Session [8eecbb40-722e-11e6-9041-c7422ee2d8e1] - page.onError - msg: SyntaxError: JSON Parse error: Unrecognized token '?'

  phantomjs://platform/console++.js:263 in error
[ERROR - 2016-09-03T23:31:51.671Z] Session [8eecbb40-722e-11e6-9041-c7422ee2d8e1] - page.onError - stack:
  parse (undefined:3)
  methodCaller_emscripten$$val_$std$$wstring$ (:3)
  __emval_call_method (https://br.ebookjapan.jp/br/reader/common/js/br_ems-7h.js:1)
  W (https://br.ebookjapan.jp/br/reader/common/js/br_ems-7h.js:6)
  B (https://br.ebookjapan.jp/br/reader/common/js/br_ems-7h.js:6)
  E (https://br.ebookjapan.jp/br/reader/common/js/br_ems-7h.js:6)
  ba (https://br.ebookjapan.jp/br/reader/common/js/br_ems-7h.js:7)
  Di (https://br.ebookjapan.jp/br/reader/common/js/br_ems-7h.js:13)
  dynCall_iii_11 (:2)
  decrypt (:6)
  __decrypt (:1)
  decryption (https://br.ebookjapan.jp/br/reader/viewer/js/viewer_engine-7h-min.js:3)
  (anonymous function) (https://br.ebookjapan.jp/br/reader/viewer/js/viewer_engine-7h-min.js:3)
  l (https://br.ebookjapan.jp/br/reader/viewer/js/viewer_util-7h-min.js:2)
  fireWith (https://br.ebookjapan.jp/br/reader/viewer/js/viewer_util-7h-min.js:2)
  d (https://br.ebookjapan.jp/br/reader/viewer/js/viewer_util-7h-min.js:3)
  d (https://br.ebookjapan.jp/br/reader/viewer/js/viewer_util-7h-min.js:3)

  phantomjs://platform/console++.js:263 in error
```

**Comment by MinoMino** [comment]
Alright, I just pushed an update to catch errors thrown by the reader, which is presumably what's happening here.

Update mindl with `python -m pip install --upgrade git+https://github.com/MinoMino/mindl.git#egg=mindl` and try again.

You will hopefully see something like this:

```
(01:40 INFO) URL is being handled by plugin: eBookJapan v0.1
(01:40 INFO) Starting download...
(01:42:03 CRITICAL) [eBookJapan] Failed to find the controller. Checking for an alert...
(01:42:03 CRITICAL) [eBookJapan] The reader threw the following error:
エラー
システムエラーが発生しました。
get_DrmData
1001／sessionなし
```

Paste the error here if that is the case, please.

**Comment by timf1256** [comment]
> (20:13 INFO) URL is being handled by plugin: eBookJapan v0.1
> (20:13 INFO) Starting download...
> (20:14:24 CRITICAL) [eBookJapan] Failed to find the controller. Checking for an
> alert...
> (20:14:24 CRITICAL) [eBookJapan] The reader threw the following error:
> \u30a8\u30e9\u30fc
> \u30d1\u30e9\u30e1\u30fc\u30bf\u304c\u4e0d\u6b63\u3067\u3059\u3002

Just to double check, am I using the correct syntax and link?

> python -m mindl -o email=my@email.com -o password=mypassword https://br.ebookjapan.jp/br/reader/viewer/view.html?sessionid=09bln11edb21bin0465l0964fl16st4c

**Comment by MinoMino** [comment]
> エラー パラメータが不正です。
> Error: The parameters are incorrect.

The link is the issue here. I think the link you copied is cut off and is missing several parameters.  Here's how a link looks on my end:

`https://br.ebookjapan.jp/br/reader/viewer/view.html?sessionid=09kkm41nba37kgm04f3k08f2e4161s3w&did=20160825162255&keydata=A32206B4CA1DFB276A942BE3676BE26E151D4F0E148AF2BE715E4D5BA7461057&shopID=eBookJapan`

The `keydata` and whatnot is missing. Also, I forgot to mention it in the readme, but make sure you put the URL in double quotes, or cmd will interpret the ampersands as additional commands instead of it being part of the URL.

**Comment by timf1256** [comment]
> The keydata and whatnot is missing. Also, I forgot to mention it in the readme, but make sure you put the URL in double quotes, or cmd will interpret the ampersands as additional commands instead of it being part of the URL.

This is what happens when I take instructions literally.  I'm sorry for wasting your time, but thank you for the help.  It's working now.

> python -m mindl -o email=my@email.com -o password=mypassword
> "https://br.ebookjapan.jp/br/reader/viewer/view.html?sessionid=098wm26b
> na288sm043gk093fe316p43v&did=2016072405153&keydata=5822450774A94E6660960B2A66123
> 1324452998A10AD28689226D95E8A240437&shopID=eBookJapan"
> (20:28 INFO) URL is being handled by plugin: eBookJapan v0.1
> (20:28 INFO) Starting download...
> (20:28:57 INFO) [eBookJapan] Starting the ripping process...
> (20:28 INFO) Creating non-existent directory 'downloads\uff3b\u7acb\u3061\u8aad
> \u307f\u7248\uff3d\u30d7\u30e9\u30b9\u30c6\u30a3\u30c3\u30af\u30fb\u30e1\u30e2\u
> 30ea\u30fc\u30ba Say to good-bye \u7b2c1\u5dfb'.
> (20:29 INFO) 20 files have been downloaded so far...
> (20:29 INFO) 40 files have been downloaded so far...
> (20:29 INFO) 60 files have been downloaded so far...
> (20:29 INFO) Done! A total of 70 were downloaded.
> (20:29 INFO) Finalizing...

**Comment by MinoMino** [comment]
Yeah, I just saw the fact that I omitted the `keydata` stuff from the URL in the example as well, so I can see how that can be misleading. My bad, I'll make it more obvious the whole URL is needed.
